### ISSUE TITLE
You have been logged out!

### ISSUE THREAD

**Issue by wvelez6** [mplodowski/oc-logout-plugin#2]
Hello, after new update I haven't been able to log back in. It says "You have been logged out!". I have the latest OctoberCMS 351 version. I had to FTP to my server and delete the logout plugin in order to get access. No logs were output.

**Comment by mplodowski** [comment]
Hi,

what session driver do you use?

Can you check your database table `system_settings` and look for item `renatio_logout_settings` what is the value there?

What if you reinstall plugin?

**Comment by wvelez6** [comment]
I had it set to an hour, "3600", drop from database, reinstalled plugin and its working now. Thanks.

**Comment by mplodowski** [comment]
I pushed an update that should fix migration to 2.0 version. You will not be affected by this update.

Now you enter session lifetime in minutes, so you should change 3600 to 60.
