### ISSUE TITLE
After logout it redirects to backend/

### ISSUE THREAD

**Issue by wvelez6** [mplodowski/oc-logout-plugin#3]
After a session logout the page redirects to a blank backend/ without domain. I re-installed and it did the same.

**Comment by mplodowski** [comment]
I cannot replicate this.

What version of OctoberCMS are you using?

Did you modify default CMS configuration?

Is your site online so that I can inspect this?

**Comment by abhi1693** [comment]
Same issue

**Comment by mplodowski** [comment]
Sorry, but without clear instuction how to replicate this I cannot help you guys.

**Comment by MilosStanic** [comment]
Same here, the full url is "backend", not prefixed with site url, not even "http://backend", just plain "backend". No idea how to replicate. I just installed and that's what happened. Could it be happening only on https sites? Because my site uses SSL.
